### ISSUE TITLE
Question about O.Enrol

### ISSUE THREAD

**Issue by FGUERINGTO** [biometricITC/cPP-biometrics#100]
Text of O.Enrol contains some ambiguity. 
The TOE shall implement the functionality to enroll a user for mobile biometric verification, only after successful authentication of the user. The TOE shall check the quality of enrolment templates in order to meet the relevant error rates for mobile biometric verification.

What is the result of the check when quality is good or wrong ?
Could we precise that successful authentication of the user has been done with Fallback mechanism, otherwise it is strange to say authentication is perform prior enrolment.

**Comment by nils-tekampe** [comment]
Closing the Issue as the corresponding PR has just been merged.
