### ISSUE TITLE
Request to review updated draft Evaluation Activity for the performance testing

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-biometrics#109]
EA for the performance testing that is originally included in the Annex of draft cPP was updated to make it simple and fit to the mobile device use case. I hope to include this draft into the Supporting Document before opening it to the public.

https://github.com/nils-tekampe/cPP-biometrics/blob/master/input/EA_Peform.md

**Comment by woodbe** [comment]
Unless there are objections, I will close this issue before the next meeting (6/13).

**Comment by woodbe** [comment]
Should have been closed earlier.
