### ISSUE TITLE
General methodology document

### ISSUE THREAD

**Issue by nils-tekampe** [biometricITC/cPP-biometrics#111]
Dear all,
The long weekend in Germany has been a fantastic chance to get into all the question around our methodology documents. While I read thru the existing proposals, I had some "de ja vues“ as I obviously discussed some of the questions that came up before. 

I currently see that we will be needing 4 dedicated test plans for the first cPP:
1. Requirements on the performance test for the developer (ATE_FUN)
2. Requirements on the performance test for the lab(ATE_IND)
3. Requirements on the PAD test for the developer (ATE_FUN)
4. Requiremenst on the PAD test for the lab (ATE_IND)
These test plans will be building the core of our methodology. 

However, I also think that we will need a general methodology document. That introduces readers to the problem and carries all the general information. And for this document I would like to make the proposal to us D6.5 (https://www.konfidas.de/app/download/10019609752/D6.5.pdf?t=1503061677) from the BEAT project. This document contains all the information on exactly this topic and has been compiled by a group of experts. Some of the authors (including myself) are also part of our iTC.

I don‘t think that we will be able to use the document as it currently is for all areas. For example, we have obviously chosen a different way to model the biometric functionality in terms of SFRs. However, D6.5 can be a very good starting point. 

To be very clear: using D6.5 does not touch any of our test plans as this is exactly the level of details where D6.5 stops. So, our test plans can be „hooked into“ the document. 

Before doing any real work in this direction, I‘d like to hear your opinions about this question. 

Regards
Nils

**Comment by n-kai** [comment]
We disscussed above Nils proposal on 7th June and agreed with it but we need more detailed plan or proposed text so that we can discuss it further. 

The following is another comment from Naruki
Assurance level of use case 1 is EAL1 that doesn't include ATE_FUN. So I am not sure if we need to include "3.Requirements on the PAD test for the developer" in our supporting document.

**Comment by nils-tekampe** [comment]
@n-kai This is a very good point. Indeed, if we are on EAL1, ATE_FUN will not be part of the assurance package. However, we often referred to the competence of the developer in our discussions. So, it may be worth considering to include an augmentation of ATE_FUN to the PP. What do you think?

**Comment by BrJu** [comment]
Issue to be discussed during tomorrow meeting! 
@n-kai @nils-tekampe  Please acknowledge in case you have new elements

**Comment by BrJu** [comment]
Framework doc 
- formal requirements may be covered by 19989 / we should use it as most as possible
=> to all, tell us if cannot have access to a copy of 19989
- toolboxes needed on iTC side
- vulnerability assessment guidance needed also on iTC

We should work on the framework doc first while discussing with NIAP to check/endorse links between MDFPP and the cPP. Toolbox/details will come later.

@nils-tekampe will propose a structure for the framework in a few weeks

**Comment by woodbe** [comment]
Unless there are objections, I will close this issue before the next meeting (6/13).

**Comment by The-Fiona** [comment]
No objection from me.
