### ISSUE TITLE
Policy for merging

### ISSUE THREAD

**Issue by nils-tekampe** [biometricITC/cPP-biometrics#115]
Hi all,
I just changed the setting for the master branch of our repository so that (as a standard user) no direct commits to master are possible (which is good practice). 
This means that all changes have to come via dedicated branches and pull requests. 
In this context, I thought that it would be useful to think about a kind of a policy for merging:
Here is my suggestion:

1. Simple changes can be merged into master after a review of two other members of the team. This can be easily enforced by github. A simple change can be:
- an editorial change
- or a change that only implements an issue for which agreement has been reached before. 
2. More complex PRs should be discussed during one of our calls. 

Please let me know, what you think.

Nils

**Comment by woodbe** [comment]
I would agree with that practice.

Brian


Brian Wood, CISSP | Device Security Certification Manager
Samsung Research America
M: +1-973-440-9125
E: be.wood@samsung.com<mailto:be.wood@samsung.com>

**Comment by BrJu** [comment]
Fully agree with @nils-tekampe  -- this is closed to what be did implicitly until now but good to have it written. And I experiment this rule with a commit on Readme.md !
