### ISSUE TITLE
cPP review request

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-biometrics#126]
I created the new branch (NK-finalchange) and added the ECD and made editorial changes to finalize the cPP.

My draft is saved at;
https://github.com/biometricITC/cPP-biometrics/blob/NK-finalchange/3_ProtectionProfile/Bio%20cPP.md

If you want to see the diff between the current version and my draft, please follow the instructions below;
1) click "Pull requests" above
2) click green box labeled "New pull request"
3) change "compare: master" to "compare: NK-finalchange"
4) click "Load diff" in blue
(I am not sure whether or not this is the best way to see the diff)

I also created the pull request to merge my changes into the current version.

**Comment by BrJu** [comment]
no need to keep this open -- please add your comments directly into the PR #127
