### ISSUE TITLE
Draft SD progress

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-biometrics#135]
I created the new branch (n-kai-SD_Patch_201808) and pull together the existing documents to update the SD. 

My draft is saved at;
https://github.com/biometricITC/cPP-biometrics/blob/n-kai-SD_Patch_201808/4_Methodology/BS%20SD.md

This draft has not been completed yet and lots of things to do to finalize it.
So it's too early for the member to review this draft but if you have any major and serious comments, please tell me in advance so that I can update the draft efficiently.

If you want to see the diff between the current version and my draft, please follow the instructions below;

    click "Pull requests" above
    click green box labeled "New pull request"
    change "compare: master" to "compare: n-kai-SD_Patch_201808"
    click "Load diff" in blue

**Comment by woodbe** [comment]
The following acronyms should be added to the table (there may be others, these were the ones I specifically came across):

FAR
FRR
FNMR
FMR
PAI
PAD
SEE
TSFI (TSF?)

Section 2.1.5 - "guidnace" instead of "guidance"
Section 5.3 - "applicalbe" instead of "applicable", "paticular" instead of "particular"
Section 5.5 - "ealuator" instead of "evaluator"

I don't see anything else off hand, but I will read through again next week as well.

**Comment by woodbe** [comment]
Is Appendix C going to stay in the SD directly or will it be placed into a separate document? I had thought that the procedures for PAD testing were going to be separate from the main SD so they could potentially be updated separately without requiring a revision to the SD itself.

I would actually recommend, if there is a way to do it, that this appendix point to a location where published/approved PAD tests for different modalities would be stored, so the SD doesn't need to be updated if new modalities are added at a later time.

**Comment by n-kai** [comment]
@woodbe 
I agree with your comment. I just included PAD testing in Appendix C because I think that it may be easier for members to review the whole document. I will move it into the separate document in the next version.
I will also add acronyms as you suggested to the next draft.

**Comment by BrJu** [comment]
@n-kai @nils-tekampe  any new input (consensus?) since last meeting on reference to 19989-1?

**Comment by n-kai** [comment]
@BrJu 
I am waiting for proposal from Nils. In my understanding, Nils said that he proposed to identify specific parts of 19989-1 that should be refered in our SD at the last meeting.

My opinion is that 1) all evaluation activities that evaluator has to follow must be described in the SD and 2) 19989-1 doesn't describe mobile specific activities so we can't refer this doc in the evaluation activities (however, we can recommend to read the 19989-1 in the introductinary part of the SD)

**Comment by woodbe** [comment]
Unless there are objections, I will close this issue before the next meeting (6/13).
