### ISSUE TITLE
CCN comment on OSP.RESIDUAL

### ISSUE THREAD

**Issue by BrJu** [biometricITC/cPP-biometrics#14]
"Audit ?" commented on the expression security relevant data

**Comment by woodbe** [comment]
While I know we had marked this a not mobile, I think we actually ended up handling this between O.Protection and the selection-based inclusion of FDP_RIP.2. I'm OK with leaving this, but I'm not sure if it is still a relevant concern based on where Use Case 1 ended up going.

**Comment by nils-tekampe** [comment]
I thought about the whole history of this discussion again and I would basically agree to close the issue. We have FDP_RIP as an optional requirement in the cPP. I‘m still astonished that the MDFPP does not contain this requirement and that it is possible to be compliant to MDFPP without residual information protection but I guess this discussion is more for the MDFPP iTC to have.

**Comment by woodbe** [comment]
Closing based on current agreement.
