### ISSUE TITLE
Iris vs Eye?

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#141]
Looking at the FIDO biometrics documentation they list it as "eye/iris, and thinking about it overall I didn't really run into anything that would prevent some holistic look at the eye as being used versus specifically the iris (though I can see some, like say a retinal image, needing very specialized equipment).

That said, would we want to keep this specifically titled as iris vs eye, or vs eye/iris?

**Comment by n-kai** [comment]
I am non-native English speaker so I don't see difference between "iris vs eye" or "eye/iris" ("iris vs eye" means the rentinal recognition is out of scope of the toolbox?)

Iris and retinal recognition are different in how they work however the same test (i.e. taking a picture of eye using NIR light and present it to the TOE) can be applied to both types of recognition so the scope of your toolbox should include retinal recognition in addition to iris.

I am creating a toolbox for vein recognition. There are several types of vein recognition including finger/palm, wrist and dorsal hand vein recognition. Test items in the toolbox are created refering research papers on finger/palm vein however the same tests are also applicable to wrist and dorsal vein. so I decided to label my toolbox as "vein toolbox".

**Comment by nils-tekampe** [comment]
I agree. At least for the first version of the toolbox I would aim at defining a toolbox for eye (including iris and retina). If we find out in the end that a further specialization is necessary, we can still split up.

--

**Comment by woodbe** [comment]
When the toolbox files are moved, the new ones will all list "eye" instead of "iris" for the titles. Since the iris is still critical for the current types of detection (whether straight photo or the NIR), there are still instructions stating the iris must be visible, but except for the specific instructions, the titles and broad directions/descriptions are "eye".

**Comment by woodbe** [comment]
Closed as files have been edited to cover eye in general and moved to the new repository.
