### ISSUE TITLE
Motivation description

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#143]
I don't have a good answer for this, but the motivation has long been a problem for me. Stating that we are only testing against friends playing around (but yet they are willing to spend money or use potentially expensive equipment to do so) I think is a little disingenuous. Not to mention I'm not sure how that really fits with the MDFPP, which doesn't protect necessarily against full-on nation-state level of attacks, is certainly more secure than "my friend is trying to get into my phone for fun".

While I can understand the potential distinction between attacks based on money, I'm not sure there really is a sufficient difference between accessing money and accessing data (or other services/apps, etc) protected by a biometric login (the main one seems to be who has to deal with the consequences of the bypass, not the level of security needed on the access control itself). I can understand different groups who may rely on the cPP for an evaluation needing different assurance, and as had been discussed in Amsterdam, I think that the real difference between level 1 and 2 will largely be about the level of testing (maybe the addition of AVA_VAN.1 for the level 2?), but that the threat itself is really the same, and the motivation is the same (it is not someone hacking for fun, they want access to what is on the device).

I think we should look at rewriting the motivation descriptions we are using to that end. I don't have specific suggested text at this time, but would at a minimum remove the "attacking a friend's device for fun" part of any description as I do not think that is a real-world threat that we would be investing time and effort for a CC evaluation into.

**Comment by woodbe** [comment]
@n-kai have you looked at how to change this regarding the SD? The only place I see this really is [6.3.1.2.2](https://github.com/biometricITC/cPP-biometrics/blob/master/4_Methodology/BS_SD.adoc#63122-new-pais-found).

If we are going to send this out for public review soon, I would like to take care of this if we can.

**Comment by n-kai** [comment]
@woodbe 
The following is my proposed change so pls tell me it's fine for you. I modified [6.3.1.2.2](https://github.com/biometricITC/cPP-biometrics/blob/master/4_Methodology/BS_SD.adoc#63122-new-pais-found) referring [3.5.1](https://github.com/biometricITC/cPP-biometrics/blob/master/3_ProtectionProfile/BiocPP.adoc#351-use-case-1-mobile-biometric-verification-for-unlocking-the-mobile-device)

I will crate the PR to implement the change if it's fine for you.

a. Attacker’s motivation
For enhanced security that is easy to use, the TOE implements mobile biometric verification on a device once it has been “unlocked”. The initial unlock is generally done by a PIN/password which is required at startup (or possibly after some period of time), and after that the user is able to use an own biometric characteristic to unlock access to the mobile device. In this use case, the mobile device is not supposed to be used for security sensitive services through the mobile biometric verification. 
Attacker may use any tools or materials that are normally available at home and normal office environment such as laptop PC or office printer to attack the TOE. Attacker may also use any services (e.g. printing services to print a high-resolution photo of target users to create a face PAI) if such services are available at low cost.

**Comment by woodbe** [comment]
This text looks fine for me. I still think there isn't any difference between the login and the sensitive services because no one implements it that way on the device, but this at least is better than an attack for fun.

**Comment by n-kai** [comment]
I created the PR #165 to implement proposed change with editorial modification.

**Comment by woodbe** [comment]
Closing based on approval and merge of #165.
