### ISSUE TITLE
Conversion of cPP to AsciiDoc

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#146]
@nils-tekampe will to a conversion of the current cPP to AsciiDoc to provide more polish.

**Comment by nils-tekampe** [comment]
BTW: One of the advantages of this data format is that it can be easily transformed into PDF. I'm attaching the current version as PDF. 
[BiocPP05.pdf](https://github.com/biometricITC/cPP-biometrics/files/2752548/BiocPP05.pdf)

**Comment by woodbe** [comment]
We will consider post-processing (through LaTex or similar) to polish things like keeping titles better (so they don't end up at the bottom of one page or have captions not with images).

**Comment by woodbe** [comment]
I am going to close this at this point. While "good looking" output is important, we will deal with that once we are ready for release, and if that means editing in something like LaTex or Acrobat or something, we will handle it then. The tools will be based on what expertise is available at that point.
