### ISSUE TITLE
O.PAD_ENROLMENT for TOE.PAD?

### ISSUE THREAD

**Issue by BrJu** [biometricITC/cPP-biometrics#15]
My original thought was: TOE.PAD should be removed.
@nils-tekampe indicated he knows some PAD systems where some kind of enrolment is needed. 

Thus the suggestion is now:  this should be made optional for TOE.PAD.

**Comment by woodbe** [comment]
This was linked to #27 which was closed. I think this should be closed as well.

**Comment by nils-tekampe** [comment]
agreed

**Comment by woodbe** [comment]
Agreed to close in 2/14 meeting
