### ISSUE TITLE
Thoughts about this graphic

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#159]
![image](https://user-images.githubusercontent.com/19575297/56986566-0ca65700-6b59-11e9-99d4-9b14fef93e28.png)

This is a general question, not a specific issue, but I am hoping to get your thoughts about the bottom graphic shown in the attached image. I am playing with a formatting tool that can take ASCII art drawings and convert them into graphic output. On the left is the AsciiDoc text that both embeds the existing graphic and then the text that generates the bottom one for comparison (yes, I have arrows on 2 and not all, so I could see the difference). This uses [ditaa](http://ditaa.sourceforge.net/).

I have been looking at this to allow the editing process to be done a little easier on the images for these items (like the extended components definitions) or other places where simple drawings are needed, as the ASCII art allows you to read the contents in text while reviewing the document (and edit it). There is a limitation in that special characters like : and - are used in the lines and so can't be added to the text, but I figure this should be acceptable. 

I haven't actually made this change in the uploaded document, I just wanted to get opinions about whether this would be acceptable for our use instead of needing to generate images separately to do the same thing.

Thanks

**Comment by nils-tekampe** [comment]
I really like it! 👍👍👍

**Comment by The-Fiona** [comment]
me too.

**Comment by woodbe** [comment]
Thanks
