### ISSUE TITLE
Update relationship to other ISO biometric standard under development

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#173]
From @ohenniger:

BiocPP and BS_SD do not reference the following related standards documents under development:      

[ISO/IEC 19989-2] Information technology -- Security techniques -- Criteria   and methodology for security evaluation of biometric systems -- Part 2: Biometric   recognition performance     

[ISO/IEC 19989-3] Information technology -- Security techniques -- Criteria   and methodology for security evaluation of biometric systems -- Part 3:   Presentation attack detection     

[ISO/IEC 19795-9] Information technology -- Biometric performance testing   and reporting -- Part 9: Testing on mobile devices     

[ISO/IEC 30107-4] Information technology -- Biometric presentation attack   detection -- Part 4: Profile for testing of mobile devices

Clarify the relationship to these documents

**Comment by n-kai** [comment]
Yes, those references should be removed from the draft. 
I will do a final check to find other errors in the draft before the public review.

**Comment by woodbe** [comment]
So thinking about the change in #175. I assume it is probably worth while to have these all listed as reference documents, so that they are all listed as related but I don't know that we need to go any further. This would also bring back the drafts (now 21879) as related, but leave the change in #175 as the one that is referenced later in the document. This may actually be a more clear point since these are all related. I created #176 to do this.

**Comment by woodbe** [comment]
This has been added to the latest release.
