### ISSUE TITLE
Solutions for PAD issue

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-biometrics#186]
There are following options to take for the PAD issue. I would like to know any view or opinion from members which option the iTC should take.

**Option 1: cPP includes AVA_VAN.1 for PAD**
The evaluator conducts both independent (ATE_IND.1) and penetration (AVA_VAN.1) testing using toolboxes which includes the latest attack. The TOE will be failed if the evaluator can find such PAI that can reliably defeat the TOE.
Pros: Current draft cPP and SD was developed following this option.
Cons: BSI claims that cPP shouldn't include AVA_VAN1 for PAD because they think that there are no biometric verification products that can prevent the presentation attack even at AVA_VAN.1 level

**Option 2: Define PAD as optional requirement** 
Make PAD an optional feature of the cPP, and thereby removing it from consideration for AVA_VAN unless PAD is selected by the vendor
Pros: We can follow the CCRA Annex K (cPP must include AVA_VAN)
Cons: We have to modify the ESR to change the PAD as an optional requirement because the current ESR defines the PAD as the essential requirement, and submit it to the CCRA for approval. But it may take several months.

**Option 3: Exclude AVA_VAN.1 for PAD from cPP** 
The evaluator conducts only independent testing (ATE_IND.1) using toolboxes which may not include the latest attack and number of trials is limited (e.g. 10 trials). The TOE will be failed if the evaluator can find such PAI (spoofing artifact) that can reliably defeat the TOE.
Pros: BSI supports this approach.
Cons: This approach doesn't follow the CCRA Annex K and the cPP may be rejected by the CCRA.

**Comment by woodbe** [comment]
I think that option 2 is our best bet right now for splitting the difference (so to speak) on the coverage for AVA_VAN. Proposing this to the CCDB may at least get a response and a direction to move.

**Comment by n-kai** [comment]
I am fine with option 1 and 2 but I disagree with option 3 because I believe that AVA_VAN evaluation is possible for certain type of biometric modalities (Three biometric TOE evaluations are ongoing with AVA_VAN.2 under Japanese scheme and I don't see any issues for AVA_VAN evaluation)

**Comment by woodbe** [comment]
@n-kai will write a new draft of the ESR based on option 2 and we will then send this to the mailing list and sponsoring schemes for feedback/comments prior to the CCDB/ICCC meetings.

@woodbe will setup a survey to gather the input from the feedback request.

**Comment by woodbe** [comment]
@n-kai created a proposed ESR and it has been distributed to the iTC. It will also be sent specifically to the scheme representatives for review.
