### ISSUE TITLE
Edit PP-Module to not be MDFPP-specific

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#187]
I am wondering if we should consider editing the PP-Module to move things like the MDFPP justifications to somewhere else (I'm wondering if these should actually be in the PP-Configuration since that actually makes more sense as the place to justify why the PP and PP-Module would go together).

I do not know if this is actually possible in terms of the expectations of the PP-Configuration document, but I am thinking here that the document would be a little more "generic" in that it relies on base-PP, but not a specific one, and that the justification which PPs it can work with should in the PP-Configuration.

Is this workable within the expectations of the PP-Configuration?

**Comment by n-kai** [comment]
I agree with you. 

Current CC/CEM V3.1.5 is not clear about it but according to the latest ISO version of CC (ISO/IEC 15408-1 CD3);

_C.3.1.5 Consistency rationale
A PP-Configuration shall provide a consistency rationale to ensure the compatibility of the combination of components (components are Base PPs and the PP-Modules that compose the PP-Configuration).
The consistency rationale shall demonstrate that the TOE overview is consistent with the TOE overview
of the PP-Configuration components and that the unions of SPDs, objectives, and security functional requirements defined in these components do not lead to a contradiction.
The consistency rationale may use correspondence tables between SPD/objectives/SFRs together with textual justifications._

**Comment by woodbe** [comment]
Noted that this should be done, probably after the ICCC, as it seems the right thing to work towards.

@woodbe will start a PR for this when he has a chance.
