### ISSUE TITLE
FIA_UAU.5 in separate section

### ISSUE THREAD

**Issue by ccolin318** [biometricITC/cPP-biometrics#193]
Why is FIA_UAU.5 separated from the other SFRs in Section 7.1? Would it make more sense to put it with the others in section 7.2?

**Comment by woodbe** [comment]
Section 7.1 should have been moved into the PPC

**Comment by woodbe** [comment]
This is now located in the PPC (though differently) here:

https://github.com/biometricITC/cPP-biometrics/blame/ea0e17d855b3173f705eb7d6caaac9d1bb911e0a/3_ProtectionProfile/PP%20config.adoc#L125
