### ISSUE TITLE
Application note 13

### ISSUE THREAD

**Issue by ccolin318** [biometricITC/cPP-biometrics#194]
The wording of application note 13 seems like its adding a requirement to this SFR. My understanding is that application notes should add context/guidance to the SFR but are not required to be adhered too. The SD for the SFR states that this is out of the scope for the EA.

**Comment by woodbe** [comment]
Need to clarify that this related to A.Alternative and the TOE environment authentication

**Comment by woodbe** [comment]
Closed as merged.
