### ISSUE TITLE
Use Protection Profile instead of PP for the first time in the document

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#203]
https://github.com/biometricITC/cPP-biometrics/blame/c52f87fc6c717c04e0d6448d17995b458d5b54d5/3_ProtectionProfile/BiocPP.adoc#L16

Instead of saying "collaborative PP-Module", write it out as "collaborative Protection Profile-Module (PP-Module)".

Issue 1 from Cybersecurity Malaysia

**Comment by woodbe** [comment]
I'm not sure about this. The PP-Modules I see just state PP-Module up front, so I don't know if this is actually a correct term (Protection Profile-Module).

**Comment by The-Fiona** [comment]
In the proposed ISO standard the definition is thus:

**Protection Profile module
PP-Module**
implementation-independent statement of security needs for a TOE type complementary to one or more Base Protection Profiles



So, I would suggest if we do spell it out on first use that we use the term "Protection Profile module" and thereafter "PP-Module"

**Comment by The-Fiona** [comment]
Plus....
"collaborative Protection Profile" is a construct of the CCDB/CCRA scheme and therefore does not appear in the ISO standard. I guess the authoritative source for that term is the CCRA committees..

**Comment by woodbe** [comment]
I'm still good with us leaving "collaborative" as a descriptor for the PP-Module. I'll make a pull request to review.
