### ISSUE TITLE
Add definitions from diagram to glossary

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#209]
Add Biometric Claim and Biometric Probe to the glossary as both are used in Figure 1.

Issues 9 & 10 from Cybersecurity Malaysia

**Comment by woodbe** [comment]
I am not sure we should add these definitions or make an adjustment to the diagram to eliminate the need for the terms.

**Comment by n-kai** [comment]
It's OK to eliminate terms but if you want to add definition, please see below that copied from ISO/IEC JTC 1/SC 37/WG 1 Harmonized biometric vocabulary

biometric probe: biometric sample or biometric feature set input to an algorithm for use as the
subject of biometric comparison to a biometric reference(s)

biometric claim: claim that a biometric capture subject is or is not the source of a specified or unspecified biometric reference

**Comment by woodbe** [comment]
@woodbe will create a PR after the call.
