### ISSUE TITLE
Add numbers to Figure 1 to describe capabilities

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#211]
Add numbers in Figure 1 to represent the capabilities of TOE.

Issue 12 from Cybersecurity Malaysia

**Comment by n-kai** [comment]
I don't think that numbers are not necessary because capabilities of the TOE can be identified through subsystem name (e.g. Data Capture Subsystem)

**Comment by woodbe** [comment]
based on 1/30 call, this will be closed as group does not feel this is necessary at this time.
