### ISSUE TITLE
Use case 1 applicability?

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#212]
Is Use Case 1  applicable for all of general purpose computing platform, such as a laptop, tablet or smartphone? 

Suggest to define the computing platform used for this scenario.

Issue 13 from Cybersecurity Malaysia

**Comment by n-kai** [comment]
The following is OK for Cybersecurity Malaysia? I update or add bold text. 

_**This use case is applicable for any computers such as desktop, laptop, tablet or smartphone that implement biometric enrolment and verification functionality**. For enhanced security that is easy to use, the computer may implement biometric verification on a **computer** once it has been “unlocked”. The initial unlock is generally done by a PIN/password which is required at startup (or possibly after some period of time), and after that, the user is able to use their own biometric characteristic to unlock access to the computer. In this use case, the computer is not supposed to be used for security sensitive services through the biometric verification._

**Comment by woodbe** [comment]
@woodbe will create a PR with the text from @n-kai
