### ISSUE TITLE
Make FPT_BDP_EXT.2/3 have consistent titles

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#215]
FPT_BDP_EXT.2 is "No Biometric data transmission"
FPT_BDP_EXT.3 is "Biometric data storage"

These are both "don't do something with biometric data in plaintext", but only one requirement states "No". 

Either add "No to FPT_BDP_EXT.3 or remove it from FPT_BDP_EXT.2.

Issue 17 from Cybersecurity Malaysia

**Comment by n-kai** [comment]
I agree to remove "No" from FPT_BDP_EXT.2

**Comment by ccolin318** [comment]
I agree with @n-kai

**Comment by woodbe** [comment]
@woodbe will create a PR removing the "No"
