### ISSUE TITLE
Should tamper evidence be added?

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#220]
If tamper is detected, the computer should be locked for a certain time before user tries again. 

Issue 23 from Cybersecurity Malaysia

**Comment by woodbe** [comment]
I don't think this is relevant to here since we are only dealing with the subsystem. The tampering report would be provided to the whole system which should then make the decision about blocking/locking.

**Comment by n-kai** [comment]
I agree with @woodbe.

**Comment by ccolin318** [comment]
I also agree with @woodbe

**Comment by woodbe** [comment]
Based on the 1/30 call, the groups feels this is not relevant at this time.
