### ISSUE TITLE
Sync storage terms

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#221]
Synch the term 'Data Storage Subsystem' with 'Storage Subsystem'.

Issue 24 from Cybersecurity Malaysia

**Comment by woodbe** [comment]
I'm not really sure this matters much. There are a few places that use data, and a few that don't, but I'm not sure it specifically matters.

**Comment by n-kai** [comment]
I think that they point out that term "Storage Subsystem" is used in Figure 1 but text under the figure 1 uses term "Data Storage Subsystem". I also made a comment requesting remove "Data" from text.

**Comment by woodbe** [comment]
@woodbe will create a PR to remove "data" from these entries
