### ISSUE TITLE
Adjust PAD in Figure 1

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#222]
To add synch Figure 1 term (Presentation attack detection subsystem) after artefact. 
Reorder this point as the last. 

Optionally detecting the presentation attacks using an artefact (Presentation attack detection subsystem). 

Issue 25 from Cybersecurity Malaysia

**Comment by n-kai** [comment]
I agree with their proposal. Current text under Figure 1 miss the subsystem name. Move text below to the last bullet and add subsystem name as they propose.

• Optionally detecting the presentation attacks using an artefact

**Comment by woodbe** [comment]
@woodbe will create a PR for this to be reviewed by @n-kai
