### ISSUE TITLE
Ensure definition consistency

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#223]
Through out the document, suggest to define user whether it is Biometric System Admin or Computer User as per glossary. 

Issue 26 from Cybersecurity Malaysia

**Comment by n-kai** [comment]
PP Module currently defines the following terms so reader can understand that the device owner acts as User = Computer User = Biometric System Administrator so no additional definition is unnecessary, 

_Biometric System Administrator
Person who is responsible for configuring the TOE. This PP-Module assumes that the user acts as
the biometric system administrator.
Computer User (User)
The individual authorized to physically control and operate the Computer. This PP-Module
assumes that the user is the device owner._

**Comment by woodbe** [comment]
Points brought up:

- since Admin and User are assumed to be the same, then maybe we should only have one common term, with a combined glossary entry
- Maybe we could have "authenticated user" and "unknown user" to distinguish between states and authorization
- could just be better clarification as to the expected role
  - this would require a description that these roles are assumed to be the same person today

Everyone will review and consider what the right approach should be.

**Comment by n-kai** [comment]
I agree 1st option. Originally bio PP was developped to be used for generic biometric system such as border control where we have admins but we shifted our focus to computer device so we don't need to define admin anymore.

**Comment by woodbe** [comment]
I created a PR for this (only towards the beginning). There are not many instances of administrator in the document, but several are potentially problematic. 

In the Extended Components Definitions for FIA_MBE_EXT and FIA_MBV_EXT list management options such as setting the TSF configuration data by the admin.

In this use case, there really isn't any management available to the user in general, so I'm not really sure how to handle this.

**Comment by n-kai** [comment]
I think that we don't need to remove management options because Extended Components Definitions for FIA_MBE_EXT and FIA_MBV_EXT should be general so that they can be applicable to more IT product other than a normal computer. This management options are also optional requirement and if the TOE is mobile or laptop, ST authors can skip this management requirement.

**Comment by woodbe** [comment]
Ok, I can accept that. I have merged the change.
