### ISSUE TITLE
Make this statement more concise

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#225]
https://github.com/biometricITC/cPP-biometrics/blame/c52f87fc6c717c04e0d6448d17995b458d5b54d5/4_Methodology/BS_SD.adoc#L16

The introduction statement to the SD is a long, run-on sentence that isn't necessarily clear.

Issue SD1 from Cybersecurity Malaysia

**Comment by n-kai** [comment]
The following text is my proposed change

This Supporting Document is “Mandatory Technical Document”, whose application is mandatory for evaluations and only those certificates issued as a result of its application are mutually recognized under the CCRA.

**Comment by woodbe** [comment]
@woodbe will create a PR with the text from @n-kai
