### ISSUE TITLE
Add document identifier to SD title

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#233]
To add identifier after the title for ease of identifying documents

Issue SD11 from Cybersecurity Malaysia

**Comment by woodbe** [comment]
I didn't create a pull request for this as I was thinking that we should probably call this [BIOSD] or [BIO-SD] as opposed to just [SD] as we have been doing. 

This is related to #224 and seems like a good idea overall.

**Comment by n-kai** [comment]
I agree, [BIOSD] or [BIO-SD] is better

**Comment by woodbe** [comment]
@woodbe will create a pull request using [BIOSD] as decided on the 1/30 call
