### ISSUE TITLE
Ongoing Evaluation of PAD Artifacts

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/cPP-biometrics#238]
[Section 6.3.1.2.2](https://biometricitc.github.io/pr-draft2/SD-BIO-enrl-v0.92DRAFT.html#_new_artefacts_found) of Supporting Document: Suppose one week after TOE completes PAD testing for Device A, a new item, Artifact X, is added to the toolbox during the evaluation of Device B. What is the requirement for ongoing testing of Device A against the toolbox? Suppose both Device A and Device B are vulnerable to Artifact X. Device A receives a pass while Device B receives a fail without a strategy for repeated testing.

**Comment by woodbe** [comment]
@gfiumara are you talking about both of these being in evaluation at the same time or that Artifact X comes up after Device A has been already certified?

Common Criteria isn't an ongoing review, so I would expect that A would have passed if it was done prior to the new artifact type and B to fail after it is available. Normally what happens in these cases is the scheme would request some sort of verification that the announced vulnerability (in this case Artifact X) is either not relevant or that an update will be made to counter it. Whether testing would be required after the update would be up to the scheme (as would what would happen to the listing if no update was provided).

**Comment by n-kai** [comment]
If artefact X is added to the toolbox, version of toolbox should be incremented (e.g. toolbox V1 to V2). Validation report need to specify the version of toolbox used during the evaluation. So Device A's validation report states A is tested based on toolbox V1 without X and Device B's report states B is tested based on V2. However, if both Device A and Device B are evaluated at the same time, scheme normally ask to evaluate both devices based on the latest toolbox version. This is how JP scheme validate the evaluation.

**Comment by gfiumara** [comment]
@n-kai Okay, in that case, I might suggest that it be made explicit that Toolbox versions be recorded in public facing documentation resulting from 6.3.1.5.

I might also suggest that there be a path for re-evaluation of *only* PAD for *only* updated items within the toolbox when new versions of toolboxes are deployed, but maybe such a suggestion is out of scope for this document.

**Comment by woodbe** [comment]
@n-kai what we may want to do is separate out the modalities into separate repositories so they can be readily versioned individually. What we probably don't want is to have changes from fingerprint to require a complete revision of all the other modalities. 

So we would do something like have the Toolbox repository which would focus on the toolbox overview and related top-level docs.

Then each repository would have just that modality, so one for Eye, Face, Vein and Fingerprint (today), and then any new modality would get its own new repository. We could take the example and build a template repository (if we want it). We don't need to mess with this right now, but we probably should do this to make the versioning easier.

**Comment by n-kai** [comment]
@gfiumara 
We can add new text about version of document as you suggested. However, PAD only re-evaluation is out of scope as you mentioned because not all CC schemes allow such partial re-evaluation.

@woodbe 
I will update the face toolbox following your suggestion.

**Comment by woodbe** [comment]
@woodbe will create the new toolbox repositories for the future move.

**Comment by woodbe** [comment]
These have been created. At the moment I created both a 2D and a 3D repository for face.
