### ISSUE TITLE
Improve Presentation Method with Sample Quality

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/cPP-biometrics#239]
[Section 6.3.1.3.1 Item c](https://biometricitc.github.io/pr-draft2/SD-BIO-enrl-v0.92DRAFT.html#_no_new_artefacts_found_test_plan) of Supporting Document: It may be useful to require a sample quality score be returned here, to make it more likely to test PAD thoroughly, rather than use presumed trial and error. Suggest adding more than just increasing time to find a better presentation method, since the requirement for the sensor to return quality scores is present elsewhere in this document.

**Comment by n-kai** [comment]
Sample quality score may not be related to possibility of successful PAD attack. In case of finger or palm vein, if the TOE measure the narrowing and widening of the blood vessels to judge whether it is artefact or not, measuring sample quality score to tune the presentation method may not help to find a better presentation and bio PP module require the evaluator to test the TOE in black box manner (i.e evaluator can't get any info how the TOE does presentation attack detection.

**Comment by woodbe** [comment]
I'm also not sure how to report a quality score for a black-box implementation. If a quality score isn't normally issued by the system (i.e. most of the mobile devices ones are a Yes/No response), I'm not sure where the quality score would come from without a LOT more changes to the system for the testing.

**Comment by gfiumara** [comment]
My initial reading of 2.3.2.5 seemed to indicate that there was some way to quantify quality, so I was suggesting that quantification perhaps be returned here as well.

**Comment by woodbe** [comment]
Yes, but there isn't any requirement there to specify how it is reported, or even what a score means, it is more of a "the vendor needs to explain their criteria", not a "the vendor must score it this way". Generally that is all handled internally to the system and not reported out, and it isn't clear why that would be meaningful if it doesn't follow a standard (like the NFIQ), unless you know a lot of details about how it is built (likely more than would be provided by this black box evaluation), to be useful in a PAD attack.

**Comment by woodbe** [comment]
The iTC doesn't feel that at this time there is any consistent or qualitative way to report on sample quality that would be useful in an evaluation.

This could be revisited in the future as biometric testing matures.
