### ISSUE TITLE
Timeframe for Penetration Testing

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/cPP-biometrics#240]
[Section 6.3.1.4](https://biometricitc.github.io/pr-draft2/SD-BIO-enrl-v0.92DRAFT.html#_conduct_the_penetration_testing) of Supporting Document: Curious as to the rationale of quantifying a single week of penetration testing when no other task in this document has a timeframe imposed.

**Comment by n-kai** [comment]
I propose to add text like "whole evaluation should be finished within 3 months and PAD testing should be finished within a single week". Smartcard evaluation supporting document define similar normal evaluation time flame to keep consistency different evaluations and BIO SD follows it.
