### ISSUE TITLE
Symmetric Verification Disclosure

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/cPP-biometrics#242]
[Section 8.1.5](https://biometricitc.github.io/pr-draft2/SD-BIO-enrl-v0.92DRAFT.html#_statistical_certainty_for_farfmr) of Supporting Document: This section has discussion of an assumption that can't be used if the verification algorithm is symmetric. Does the documentation require disclosing if the algorithm is symmetric? 
- Yes: is it required to _verify_ that it is symmetric?
- No: it should be required to be documented because of this statement.

**Comment by n-kai** [comment]
SD doesn't require evaluator to verify that it is symmetric based on some evidence like design doc. But evaluator should ask developer about the algorithm if cross-comparison of attempts/templates for ordered pair is included to make sure that the developer do the right performance test.

**Comment by woodbe** [comment]
@n-kai will make a pull request to clarify this and make it clear the vendor must describe their algorithm's symmetric comparison.

**Comment by n-kai** [comment]
@gfiumara I updated sample-quality branch to address #242

**Comment by woodbe** [comment]
Closed by #262
