### ISSUE TITLE
Which Fingers are Used?

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/cPP-biometrics#243]
[Section 8.1.5](https://biometricitc.github.io/pr-draft2/SD-BIO-enrl-v0.92DRAFT.html#_statistical_certainty_for_farfmr) of Supporting Document: Intra-individual compares are not permitted, but what about interdigital? Can we compare little fingers to ring fingers as part of a cross-comparison? If so, is this fair? Testing routinely shows dramatically different performance of different fingers, likely due to hand morphology. Can we treat them all identically?

**Comment by n-kai** [comment]
SD is developed based on ISO/IEC 19795-1 and it define the cross-comparison as every sample feature is compared against every non-self template so it's OK to compare User A's little finger with User B's ring finger. It may be odd but that's the role of standard (i.e. it's fair if everyone allow this)

**Comment by woodbe** [comment]
Closed based on 2/27/20 call.

Should consider if a more robust test protocol would be useful in later update.
