### ISSUE TITLE
password vs alternative authentication factor/mechanism

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#265]
Going through the BIOSD there are a lot of places (about 10, so not a huge number, but still) where it is explicitly stated the user enters a password (or in some cases a PIN, password or other secure method). While we do explicitly define a Password Authentication Factor, we generally talk about an alternative authentication mechanism in the PP-Module, not a password.

What I am thinking here is that we should replace the password in the BIOSD with something along the lines of "alternative authentication credential" and maybe add a definition for this in the BIOSD? I don't want to get into specifying password or PIN (or anything else), but right now it is very prescriptive in the BIOSD in many places that it MUST be a password that is required, which technically precludes a PIN (or something else, like maybe a smart card?), and I don't think that is what we want.

The problem is that we probably need to add the definition to the PP-Module for consistency and there we only have the PAF. I'm wondering if we should change PAD to Authentication Credential, and define it as a "something you know" type of thing, which would eliminate confusion about the biometric (I think).

**Comment by n-kai** [comment]
My suggestion is replacing **password** with **authentication factor** and add the following term to 2.5. Glossary in PP-Module. I use https://www.iso.org/obp/ui#home to define the following term.

**Authentication factor**
**evidence to assert the identity of an individual (e.g. ID card, smartcard, PIN, password)**

**Comment by woodbe** [comment]
This works for me. I was working on a full review of everything else and didn't want to get this tied into that update. I will post this tomorrow
