### ISSUE TITLE
Comments on Mobile Device Biometric System Use Case document

### ISSUE THREAD

**Issue by BrJu** [biometricITC/cPP-biometrics#30]
Those comments relate to [this doc](https://github.com/nils-tekampe/cPP-biometrics/blob/master/input/MobileUseCase.md#mobile-device-biometric-system-use-case) from @woodbe and @n-kai.

[Background](https://github.com/nils-tekampe/cPP-biometrics/blob/master/input/MobileUseCase.md#background) : 
- a biometric system may be capable of only part of the list.
- to the last paragraph, I would add: It is also possible that the biometric system on the mobile device is a subpart of a larger biometric system that is partially implemented outside the mobile device. 

[use cases](https://github.com/nils-tekampe/cPP-biometrics/blob/master/input/MobileUseCase.md#use-cases)
- Am I correct when seeing use case 1 as the only one related to MDF PP?
- Between use case 1 (no lab testing) and use case 2 (independent testing), how would we define the category of mobile biometric system for which the requirement is for the lab to only repeat vendor testing.
- I see, following my comment on background, at least one additional use case. 

Use case 6: Where data are sent to another device/server. Mobile device here mainly as sensor + PAD (possibly) + communication engine. Generally for more sensitive applications where you do not trust the device for the decision, which would imply higher security requirements

**Comment by woodbe** [comment]
Closing based on agreement
