### ISSUE TITLE
[NIAP] PP-Module must identify all of the Base-PPs

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#300]
Section 3.2 - The PP-Module must identify all of the Base-PPs/PP-Module Bases in the PP-Module; it can't be part of the PP-Configuration. The current structure would fail ACE_INT.1.1C and ACE_INT.1.2C in r5, and ACE_INT.1.1C, ACE_INT.1.3C, ACE_INT.1.4C, ACE_INT.1.5C, and ACE_INT.1.9C in 15408-3.

**Comment by n-kai** [comment]
@woodbe 
this comment refers CC V3.1.5 and 15408. Which should we follow to update PP and SD, CC or 15408 or both?

In the past, Mary said to me that you should follow the CC V3.1.5 not ISO 15408. 
If NIAP requires us to follow ISO, please ask which version of ISO 15408 we should follow. 

ISO 15408/18045 is currently under revision and FDIS (almost final version) ISO 15408 and 18045 will be published soon for the FDIS ballot. The ballot will take two or three months  (There may be lots of editorial changes would be made to FDIS version based on comments received during the ballot) and then 15408 and 18045 will be officially published if there is no negative vote against the FDIS ballot.

**Comment by woodbe** [comment]
@n-kai I have requested their guidance on this from them to see what they say.

**Comment by woodbe** [comment]
The recommendation from NIAP is to follow r5 at this point as the CCRA will still have to manage the transition from r5 to ISO, and r5 is approved now.

**Comment by n-kai** [comment]
OK. My recommendation is as follows.
1. Follow R5
2. If ISO give us more detail information (especially specification of PP module and configuration), follow such information to update our document
3. If there is an inconsistency between the two, follow R5 with notes so that we can update it in the future when ISO is approved by NIAP

**Comment by n-kai** [comment]
I updated PPM/PPC/SD in assumption branch to fix this issue (I should have created new branch and created a PR)
