### ISSUE TITLE
[NIAP] Consistency rationale

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#302]
Chapter 4: As with the identification of the Base-PP/PP-Module Base, the consistency rationale cannot be contained in the PP-Configuration. The PP-Configuration does not have a "place" for this information (see sections B.14.1 and B.15.1 in CC3.1r5 Part 1). This fails the entire ACE_MCO.1 SAR in both r5 and 15408-3.

Related to #300.

**Comment by n-kai** [comment]
I updated PPM/PPC/SD in assumption branch to fix this issue (I should have created new branch and created a PR)
But need further update (I will do that in April)
