### ISSUE TITLE
[NIAP] Assumptions

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#303]
Section 6.3, Assumptions: A PP-Module will only be evaluated with its base PP/PP-Module Base, so the assumptions section should take that into account. There should not be assumptions on the base PP because those requirements will be evaluated when the TOE is evaluated against the PP-Configuration, and so the ST should not have those assumptions included. Recommend deleting the first two assumptions. Note this will drive changes to section 7.2 as well.

**Comment by n-kai** [comment]
We developed the standalone Bio-cPP (not PPM) at first, and then converted it to PPM for mobile use. All assumptions were defined assuming we were developing standalone PP.  

I agree to remove first two assumptions and also propose to remove the last one.
**A.User** can also be covered by MDFPP assumptions (e.g. A.CONFIG in MDFPP) and I don't think that TOE guidance needs to include any additional instructions for such secure configuration for mobile biometric function.

**A.User
It is assumed that the user configures the TOE and its environment correctly in a manner to ensure that the TOE security policies will be enforced.**

**Comment by woodbe** [comment]
@woodbe will remove the A.User as well
