### ISSUE TITLE
[NIAP] FIA_MBV_EXT.1.1 application note

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#305]
Section 8.2.3, FIA_MBV_EXT.1.1, application note 13: First, the application note is mis-written (we think), because it tells the ST author they must select all modalities for which Evaluation Activities are defined. We think the intent is that the ST author may only select modalities for which there are evaluation activities, but that's not what the application note says.

However, more of a concern is the structure where the SFR allows a set of choices, but the choices are restricted by the list of evaluation activities. This is not something that's been done before, and is questionable from a CC perspective. Further, looking at the SD, the EA for FIA_MBV_EXT does not give any help with respect to what modalities are allowed or not, nor does it make it clear how to deal with the open assignment. It seems that as long as we write a "Developer's performance report and its assessment strategy" and fill in all the sections, we would be good to go. It's only when the toolbox is used (which is still in draft) where there's some restriction (because only certain modalities are addressed in the PAD testing), and this is only used for FIA_MBE_EXT.3 and FIA_MBV_EXT.3, both of which are optional requirements.

Most important, there shouldn't be requirements that depend on the SD to determine what selections are allowed, and having an open assignment for the modality is contrary to the goal of objective, repeatable, etc.. If there isn't an EA defined, then there's no reason to have it as a selection. Our recommendation is to limit the selections allowed to those that explicitly have SDs defined that have measurable and repeatable SDs. Saying "write a report with these sections" is not measurable and/or repeatable (although this is more of a comment on the SD).

**Comment by ccolin318** [comment]
There seems to be 3 issues wrapped up in this comment:
1) The SFR should not allow for selections where there are no EA's defined to aid in repeatability etc. (therefore, the selections themselves may need to be updated and the "other modality" assignment removed)
2) The application note needs to be reworked to be more clear. (this seems like an easy fix)
3) The EA defined in the SD is not strict enough (requiring a developer's performance report) and does not provide specific activities for specific modalities. Should the EA look more like the FIA_BMG_EXT.1 activities in the Mobile Device Fundamentals PP v3.1?
These are just my initial thoughts on addressing this comment.
