### ISSUE TITLE
[NIAP] SD strict guidance needed

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#310]
SD (general): There are several items listed (assessment criteria for samples, for example) that are provided by the vendor but used as SD-like guidance for the evaluators. Without strict guidance on what these have to contain, the vendor can write anything. This does not to fit with the objectives of repeatable, consistent evaluation activities for the same requirements.

**Comment by woodbe** [comment]
@ccolin318 while there are several clear sections around the assessment criteria, do you have any other specific areas where you think we should look hard (I think I saw a few minor ones, but right off the top of my head I don't recall them).

**Comment by woodbe** [comment]
I haven't started writing this section yet, but I am looking at the "Developer’s performance report and its assessment strategy" section as the basis for it. I don't think we will need to get into individual details at this point for each modality, but we don't have an outline of what we expect listed anywhere. 

My thought really is that we take the Biometric quality paper we have linked and put together an expectation that if they aren't pointing to something like NFIQ or ISO 29794-4/5/6 (at least for face/fingerprint/iris, I haven't been able to find anything for standards like this for vein, though I did find #341), that they need to provide some sort of analysis that would be based on one of these. So I think that we can write something up using the information in the quality reviews to provide a guide for the assessment in general (and the evaluator already should be familiar with these papers for more information about the modalities), and we will be good.

Does anyone have any thoughts about this approach? I will try to complete it by the end of next week.

**Comment by n-kai** [comment]
@woodbe 
What kind of evaluation activities should be defined in the BIOSD? Are you thinking of the following activities?
- The evaluator needs to review the BMD to check that TOE's quality scoring algorithm conforms to those standard or technical paper. (However, TOE's quality scoring algorithm may be customized and evaluator may see some deviation from those standard or paper)
- The evaluator needs to test the TOE that the TOE reject any samples that are below the quality score

**Comment by n-kai** [comment]
@woodbe 
_Does anyone have any thoughts about this approach? I will try to complete it by the end of next week._
I agree with your direction and don't have any other questions so please go ahead and create the PR.
