### ISSUE TITLE
[cPP CHANGE] Promote application note regarding sufficient quality

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/cPP-biometrics#314]
**What is the change request for the cPP/PP-module? Please describe.**

Application note:
> ST author may refine "sufficient quality" to specify quality standards if the TOE follows such standard.

I am thinking this application note should be appended to FIA_MBE_EXT.2.1. I think it enhances the overly-ambiguous "sufficient quality" and avoids normative language in an application note (#304). 

**Describe the solution you'd like**
> *FIA_MBE_EXT.2.1* The TSF shall create templates of sufficient quality. If the TOE follows a specific quality standard, ST author shall quantify "sufficient quality."

This also promotes the MAY to a SHALL.

**Additional context**
See also #304.

**Comment by woodbe** [comment]
I think we may have taken this from ISO work (I remember we took SFRs from that early on, I don't fully remember the provenance though). That said, we could adjust the SFR to be something more like:

> The TSF shall only use samples that meet [assignment: specify quality standards] to verify the user.

From there we could adjust the app note to clarify that the ST author could either point to a specific standard being used or to define their internal standard. Maybe this is a little less ambiguous (maybe)

**Comment by woodbe** [comment]
The current requirement in the MDF reads as this:

> The TSF shall only use biometric samples of sufficient quality for enrolment. As such, sample data shall have [assignment: quality metrics corresponding to each biometric modality].

There is a similar requirement for verification (which we will need to change here also). 

I think the big thing here is that for the MDF, this is an objective requirement, so the vendor can select it as needed, while we make it mandatory, and so need to provide a means for specifying something. The issue, as I see it, is that a vendor may not actually meet some externally defined standard (such the NFIQ), but have their own. This means to me that we need to either guide the vendor via the app note that they can fill in anything in the assignment, or that we explicitly put a selection there that says:

[selection: no independent quality metric, [assignment: quality metric standard]]

I don't think we need to use the "corresponding to each biometric modality" here.

And then an "independent quality metric" would be defined as some sort of external (i.e. not defined by the vendor) standard, such as NFIQ, that could be referenced, while if the "no" option is specified, the vendor would have to provide a description of the metric that is used to determine quality in the TSS (confidential portion). And the SD should provide some idea as to what the evaluator should look for in such a document (if what we have currently isn't sufficient, I'm not certain).
