### ISSUE TITLE
base PP vs Base-PP

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#316]
So we have an inconsistency I would like to resolve during the update to v1.1. In the PP-Module I see that we have "Base-PP" to reference the MDF (or whatever), while in the SD we have "base PP".

NIAP is using Base-PP, though I could swear that I had this discussion a long time ago with @The-Fiona (probably in the iTC Team Tools, though I can't find it in any issues off hand) that it should be "base PP" based on the ISO work, and not Base-PP as NIAP has been using.

In the end, I really don't care which one is "right" but that we be consistent across all the documents.

So I would like some opinions on which one is technically correct (or not) that we should use. I'm also going to reach out to some other people in general to see if there is iTC consensus.

**Comment by woodbe** [comment]
(From @The-Fiona)

The current CC drafts and the forthcoming ISO revision differ.
The current CC I think mostly uses the capitalized form, with excursions into lower case. Ditto the hyphen!

The consistent term in the new ISO revision is

3.13
base Protection Profile
base PP
Protection Profile specified in a PP-Module used as a basis to build a PP-Configuration
3.14
base PP-Module
PP-Module specified in a different PP-Module used as a basis to build a PP-Configuration
Note 1 to entry:      Specifying a base PP-Module in a PP-Module implicitly includes the base PP-Module’s PP-Module Base.

**Comment by woodbe** [comment]
My thinking is that we use the ISO term of "base PP" simply because they have been consistent about it, not for any other reason. Does anyone have a different thought? Ensuring that we are consistent will make it easier to update later if we need to.

**Comment by woodbe** [comment]
And then another person I asked thinks we should use "Base-PP" as NIAP does, and points out that this is in R5, so maybe we should go with that. I just want to make sure we are consistent, not which one we use.

**Comment by gfiumara** [comment]
We use ISO spelling (e.g., "enrolment"), so would suggest ISO's "base PP," but much like @woodbe, I couldn't care less as long as it's consistent.

**Comment by woodbe** [comment]
@gfiumara I had assumed the spelling was actually because we were supposed to be using the King's English (or UK or something along those lines), and not because that was ISO, so I didn't know that.

The only reason I would probably lean to the Base-PP at the moment is that it is in R5 which is the current standard while the ISO will not be released until later this year (and it isn't clear how much later right now).

**Comment by gfiumara** [comment]
@woodbe I may have made that assumption myself, but enrolment is from [ISO 2382-37](https://www.iso.org/obp/ui/#iso:std:iso-iec:2382:-37:ed-2:v1:en) ("Vocabulary - Part 37: Biometrics").

**Comment by ccolin318** [comment]
I am also leaning towards Base-PP (but I tend favor the NIAP way of doing things).

**Comment by gregott** [comment]
I am probably the least knowledgeable on this topic of anyone in this group.  So take my opinion with the appropriately sized grain of salt.  I think if our documents are more closely associated with NIAP documents, then be consistent with how NIAP does things.  On the other hand if our document is primarily associated or belongs with ISO documents, then use ISO conventions.

**Comment by woodbe** [comment]
So I think the strongest argument either way is that CC 3.1R5 has Base-PP and is the current spec. The ISO version is still in draft, should be published by the end of the year (though no guarantees), and even after that still needs to be accepted by the CCDB as the approved version for it to take precedence in terms of mutual recognition as the "current" version. If/once the ISO version is accepted, this change can be made in an update after that, but in the meantime we should probably stick with CC 3.1R5.

In the end I don't think this really matters one way or the other, but not being consistent bugs me. If everything had been one way, I wouldn't have brought it up (regardless of which way it was written).

**Comment by woodbe** [comment]
@woodbe will make a pull request with the change to Base-PP across all the docs.
