### ISSUE TITLE
Comment on T.PA_Verification

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-biometrics#33]
T.PA_Verification
(This threat is missing in the integrated cPP but should be there)
An attacker may attempt to get impersonated (during verification process) as a legitimate user without being enrolled in the system themselves. In order to perform the attack, the attacker uses artificial biometric characteristics, carrying the biometric characteristic of the attacked user (as so called Presentation Attack)  

(Proposed text for use case 2 mobile biometrics cPP)
T.Presentation_attack
An attacker may attempt a presentation attack to the TOE. In order to perform the attack, the attacker uses any Presentation Attack Instrument (PAI) except their own biometric characteristic.
Note: Acquisition of biometric characteristic may be cooperative or non-cooperative.

Rational
1)	Presentation attack to enrollment should be optional
See https://github.com/nils-tekampe/cPP-biometrics/issues/27

2)	Replace “artificial biometric characteristics” with “presentation attack instruments”
Presentation attack is defined as “presentation to the biometric data capture subsystem with the goal of interfering with the operation of the biometric system” in ISO/IEC 30107-3 and “The object or characteristic used in a presentation attack is a presentation attack instrument (PAI)” as defined in ISO/IEC 30107-1. PAI can include artificial, human and other natural object as described in the ISO/IEC 30107. 
 
Presentation attack should not be limited to artificial one because the cPP should be modality independent and for example, animal or plant based object which is not categorized to artificial one can be used for presentation attack to finger vein authentication.

However PAI can be variety of objects including severed finger that can’t be used for CC evaluation. cPP needs to define an assurance activity that instructs evaluator what type of PAI should be considered. We can discuss this later during creating SFRs and related assurance activities.

This is related to issue #3 (https://github.com/nils-tekampe/cPP-biometrics/issues/3)

3)	Remove “carrying the biometric characteristic of the attacked user (as so called Presentation Attack)”
Attacker may create masterprints without “carrying the biometric characteristic of the attacked user” (*1). It’s not certain that such attack should be considered in the assurance activity for this cPP but we can discuss this later.
*1)https://www.nytimes.com/2017/04/10/technology/fingerprint-security-smartphones-apple-google-samsung.html

4)	Add note for acquisition of biometric characteristic
According to the ISO/IEC 30107-3, “Attackers may acquire a capture subject’s biometric characteristic directly from the capture subject. Such acquisition may be cooperative (e.g. the capture subject provides a fingerprint to a sensor) or non-cooperative (the capture subject leaves a fingerprint on a glass or a biometric capture device allowing the attacker to lift the fingerprint)”. T.PA_Verification should cover both cooperative and non-cooperative acquisition. See more info in “4.5.8 Access to Biometrics characteristics” in BEAT project report (https://www.beat-eu.org/project/deliverables-public/d6-5-toward-common-criteria-evaluations-of-biometric-systems).

**Comment by woodbe** [comment]
Closing due to not testing this type of PAD (such as cadavers).
