### ISSUE TITLE
Point to quality paper vs ask vendor

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#339]
https://github.com/biometricITC/cPP-biometrics/blame/b9a70e87cfe401d0beb66a60ab01884e999a2676/Supporting%20Documents/BS_SD.adoc#L520

I am thinking that maybe this should point to a quality paper instead of telling the evaluator to ask the vendor about creating low quality samples. The point of adding the paper was to provide guidance about quality, so it would seem that based on that the evaluator should be able to try. I don't have an issue stating that if you can't, then ask, but I would expect that based on the documentation about samples the evaluator should be able to do this.

**Comment by n-kai** [comment]
@woodbe 
My concern is that such quality papers or standards may not exist for some quality scoring algorithm that the TOE implements. So I might add additional text to your PR.
