### ISSUE TITLE
File list and crypto?

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#340]
https://github.com/biometricITC/cPP-biometrics/blame/b9a70e87cfe401d0beb66a60ab01884e999a2676/Supporting%20Documents/BS_SD.adoc#L600

While I get this description, it seems like we don't have anything about where the file list is supposed to be documented or where it comes from. Is this something the vendor provides (the filenames or filename standard used for generated files) or something the lab generates as part of the test.

Also, the point about the correct crypto seems like it could cause problems as we don't explicitly rely on crypto for the eval, so saying that the files need to be encrypted and that we need to know how, where is the SFR that actually states that? That isn't how the FPT_KST_EXT.1 requirements works.

I think this probably needs to be modified into something like "evaluator looks for new files that they think may be related to biometrics" followed by a "is this readable or encrypted" and then expect that the FPT_KST_EXT.1 SFR handles how this is protected (whether you can find a meaningful file, and how it is protected).

**Comment by n-kai** [comment]
@woodbe 
Description you mention is evaluation activity for FPT_BDP_EXT.3 (The TSF shall not store any plaintext biometric data outside the security boundary of the Secure Execution Environment) and we received the following comment from NIAP on evaluation activity for FPT_BDP_EXT.3)

_Section 8.3.3 ,FPT_BDP_EXT.3.1: This comment is more on the SD activity. This activity talks about encryption, and in terms of NIAP PP-Modules and PPs we require any cryptographic requirements to be specified. The SD currently indicates that the vendor gives a list of cryptographic mechanisms used--this is not acceptable. **This PP should** either specify what is required (ideally through either optional requirements or selection-based requirements) and/or **point to requirements in the Base PP**._

So I think that we can delete this test but as I commented in #333, vendor needs to point crypto functions the biometirc system uses to crypt requirement in MDFPP instead.

**Comment by woodbe** [comment]
@n-kai So FPT_BDP_EXT.3 was changed to focus on the the runtime processing instead of storage, and storage is handled by FPT_KST_EXT.1, which is part of the MDF. So I am not sure that we still need to have the requirement about crypto because that would be handled as part of the FPT_KST_EXT.1 and so not one of our SFRs.

**Comment by n-kai** [comment]
@woodbe OK, we don't need to pointer to crypto requirement in MDFPP now and we will come back this issue again if NIAP make the same comment again.
