### ISSUE TITLE
Vein quality reference

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#341]
I realized while looking at the quality section that we don't have something specifically for vein. I found this link which I think will probably work, but am not certain:

https://link.springer.com/chapter/10.1007/978-3-030-27731-4_1#Sec21

I think we should add this to the list of references and then set mentions to the quality docs to point to both the current one as well as this one.

If there is a better reference though I would definitely take it.

**Comment by n-kai** [comment]
@woodbe 
I need to ask our vendor that was certified under our scheme so please give me some time to check this.

**Comment by woodbe** [comment]
@n-kai I have added this reference for now, but we can add others as well.
