### ISSUE TITLE
Supporting Document v1.1 Section 6.5

### ISSUE THREAD

**Issue by xahun** [biometricITC/cPP-biometrics#373]
Supporting Document v1.1 Section 6.5 - it is unclear why this section references the subsection, which is an application note, to define a seemingly required evaluator activity.  It seems the 6.5.1 header and the preceding reference should be removed.  However, this ATE_IND activity seems entirely dependent on optional requirements FIA_MBE_EXT.3 and FIA_MBV_EXT.3and the seemingly mandatory test reference should be removed here and included with those optional requirements where they belong.

**Comment by woodbe** [comment]
So I think the reason this is broken into subsections has more to do with the expectation that this module could support more than one Base-PP, and so additional text could be added with different subsections that would be targeted to individual Base-PPs.

Given that at the moment we only support MDF, it is probably OK to just remove this for clarity.

(This isn't intended to say anything about the optional nature, only the headings).

**Comment by woodbe** [comment]
Add section 5.1.1.5.2 Strategy for ATE_IND between the paragraphs in 5.1.1.5.1

Remove "As explained in the [Chapter 7, Evaluation Activities for PAD testing](https://biometricitc.github.io/v1.1/1.1PRE/SD-BIO-v1.1.html#_evaluation_activities_for_pad_testing), details of PAD testing for ATE_IND.1 are defined in [[Toolbox]](https://biometricitc.github.io/v1.1/1.1PRE/SD-BIO-v1.1.html#Toolbox)." from the 6.5.1
