### ISSUE TITLE
Supporting Document v1.1 Section 6.6

### ISSUE THREAD

**Issue by xahun** [biometricITC/cPP-biometrics#374]
Supporting Document v1.1 Section 6.6 - it is unclear why this section references the subsection, which is an application note, to define a seemingly required evaluator activity.  It seems the 6.6.1 header and the preceding reference should be removed. Also, the note in section 6.6.1 indicates ATE_IND.1 and it should refer to AVA_VAN.1 instead.  It is unclear whether this activity is dependent on the optional requirements FIA_MBE_EXT.3 and FIA_MBV_EXT.3 or is actually mandatory.  The introduction in section 7.1 seems to suggest even the AVA_VAN.1 tests are related to optional requirements and therefor optional - this should be very clear at this point.

**Comment by woodbe** [comment]
So I think the reason this is broken into subsections has more to do with the expectation that this module could support more than one Base-PP, and so additional text could be added with different subsections that would be targeted to individual Base-PPs.

Given that at the moment we only support MDF, it is probably OK to just remove this for clarity.

(This isn't intended to say anything about the optional nature, only the headings).
