### ISSUE TITLE
Supporting Document v1.1 Section 7.2 ATE_IND.1

### ISSUE THREAD

**Issue by xahun** [biometricITC/cPP-biometrics#375]
Supporting Document v1.1 Section 7.2 ATE_IND.1 - the identified tests are specifically for FIA_MBE_EXT.3 and FIA_MBV_EXT.3, so they should be moved.  As written it appears that those tests must always be performed, but based on statements found for those requirements, reference to those requirements in this section, and statements in the toolbox introduction it becomes clear these test activities go with these optional SFRs.  In any case, it should be very clear that this is optional and the conditions that would require it.

**Comment by n-kai** [comment]
I agree. We changed FIA_MBE_EXT.3 and FIA_MBV_EXT.3 to optional in the cPP at the last stage of development without modifying SD.  Some text should be added under "7. Evaluation Activities for PAD testing" to make clear that these activities are optional and shall be applied if FIA_MBE_EXT.3 or FIA_MBV_EXT.3 are selected.
