### ISSUE TITLE
SD section 2.4.2.4 lists the wrong SFR

### ISSUE THREAD

**Issue by chapman-s** [biometricITC/cPP-biometrics#399]
**What is the change request for the BIOSD? Please describe.**
SD section 2.4.2.4 item "a." should reference FPT_PBT_EXT.1 instead of FPT_BDP_EXT.1.

**Describe the solution you'd like**
a. TSS shall explain how the TOE meets FPT_PBT_EXT.1 at high level description

**Describe alternatives you've considered**
a. TSS shall explain how the TOE meets FPT_PBT_EXT.1 by providing a high level description

**Additional context**
none

**Comment by woodbe** [comment]
Merged into Interpretation
