### ISSUE TITLE
NIST 800-63B Draft 4 comments

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#401]
Place to record draft comments

Comments that everyone agrees with will be submitted as from the iTC. Others should be submitted individually.

**Comment by woodbe** [comment]
PAD testing program comment

**Comment by woodbe** [comment]
Are mobile devices considered multi-factor when used as a biometric and something you have?

**Comment by woodbe** [comment]
Timeout period of forced 30 seconds after initial limit has been reached

**Comment by woodbe** [comment]
50 attempts without PAD seems very high if the system is on the low-end of acceptable FMR, even with it being part of MFA

**Comment by woodbe** [comment]
How is the relation between no-PAD and PAD (the 1:2 relation) determined? Is this the correct ratio?

**Comment by woodbe** [comment]
[sp800-63-4-suite-ipd-comment-BIO-iTC.xlsx](https://github.com/biometricITC/cPP-biometrics/files/10795698/sp800-63-4-suite-ipd-comment-BIO-iTC.xlsx)

Initial version of the comment sheet.

**Comment by woodbe** [comment]
[sp800-63-4-suite-ipd-comment-BIO-iTC-0222.xlsx](https://github.com/biometricITC/cPP-biometrics/files/10803962/sp800-63-4-suite-ipd-comment-BIO-iTC-0222.xlsx)

I have updated the comments based on the latest update from @n-kai. Please take a look.

**Comment by gfiumara** [comment]
I don't have any issue putting forward Comments 1-8.

**Comment 7**
 * Typos ("internatioal", "refered") on Comment 7

**Comment 9**
 * What do you think about altering our suggestion to include information about reporting the demographics of test subjects? I understand the rationale behind the current suggestion, but this does not prevent releasing information about the breakdown of subjects in the test. Such information could be used to determine if a test was appropriately balanced in the future once a standard is released to determine such things. Perhaps appending something like:
    > In lieu of published standards on how to achieve statistically-sound demographic biometric performance testing, testing reports of biometric authentication technologies SHALL provide information about the demographic breakdown of test subjects whose biometrics were used in performance analysis.

**Comment by woodbe** [comment]
[sp800-63-4-suite-ipd-comment-BIO-iTC-0303.xlsx](https://github.com/biometricITC/cPP-biometrics/files/10882591/sp800-63-4-suite-ipd-comment-BIO-iTC-0303.xlsx)

I have made the changes as suggested by @gfiumara in this version of the document.

**Comment by woodbe** [comment]
[sp800-63-4-suite-ipd-comment-BIO-iTC-0307.xlsx](https://github.com/biometricITC/cPP-biometrics/files/10910848/sp800-63-4-suite-ipd-comment-BIO-iTC-0307.xlsx)

Updated with @gregott comment

**Comment by woodbe** [comment]
Comments sent
