### ISSUE TITLE
NIST 800-63B 50 biometric attempts before lock

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#405]
https://github.com/biometricITC/cPP-biometrics/issues/401#issuecomment-1402145728

### Comment

50 attempts without PAD seems very high if the system is on the low-end of acceptable FMR, even with it being part of MFA

**Comment by gfiumara** [comment]
Suggested change: reduce the number of allowable attempts, or clarify why 50 attempts is an acceptable value.

**Comment by woodbe** [comment]
agree on the suggestion

**Comment by gregott** [comment]
I agree as well. Some sort of penalty should be invoked well before 50 failed attempts.

**Comment by woodbe** [comment]
Add possible tie to delays between attempts as part of the suggestion.

**Comment by woodbe** [comment]
Suggested Change:

The number of attempts allowed should be lowered or justified as to why the number of attempts and the included delays are acceptable. It seems that the number of attempts should be tied to the FAR/FMR value of the system, and not globally defined. Possibly a table showing acceptable FMR values and a range of allowed attempts.
