### ISSUE TITLE
Comments on NIST 800-63A

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-biometrics#408]
Sorry but I am not sure if this topic was discussed at the last meeting.

NIST is requesting to review the draft NIST 800-63A (*1)  on the following topics for Identity Proofing and Enrollment (See L199-203)

_• Are current testing programs for liveness detection and presentation attack detection sufficient for evaluating the performance of implementations and technologies?
• What impacts would the proposed biometric performance requirements for identity proofing have on real-world implementations of biometric technologies_

So it seems that NIST wants to see comments on "5.1.8. Requirements for Use of Biometrics". We can make, for example, following comments to promote our activities.

[Comment 1]
The CSP can rely on the mobile device biometric verification instead of doing it by itself. For example, L483-486 can be extended when the CSP uses the biometrics (of course the CSP needs to develop an app to make sure that the applicant finishes the biometric verification before providing the code but the cost of app development is much cheaper that the developing the biometric verification system in the CSP).

_c) The CSP sends an enrollment code to the validated phone number of the applicant, the applicant provides the enrollment code to the CSP **after finishing the biometric verification by the mobile device**, and the CSP confirms they match, verifying they the applicant is in possession and control of the validated phone number_

[Comment 2]
We can make comments on those requirements in 5.1.8, for example...

_6. CSPs SHALL have all biometric algorithms tested by an independent entity
(e.g., accredited laboratory or research institution) for performance, including
performance across demographic groups.
7. Testing of all algorithms SHALL be consistent with published ISO/IEC standards
for the given modality._

NIST should define minimum requirement to conduct performance testing. Result of testing may be useless if there is no such requirements (for example, lab may test the biometrics using only 10 volunteers with many attempts from the same volunteer). I don't know the ISO/IEC standards that specify such minimum number (may be in 19795-9? but this is not IS but TS) but [BIOSD] may be useful document to refer for the testing.

*1) https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63A-4.ipd.pdf

**Comment by woodbe** [comment]
drop the first comment per @n-kai
