### ISSUE TITLE
[IT REQUEST] Incorrect Management SFR title

### ISSUE THREAD

**Issue by mpdool2** [biometricITC/cPP-biometrics#422]
**Before submitting your request, please check https://biometricitc.github.io/TD/tech-dec.html for the current set of Technical Decisions.**

**Requesting Organization: **
NIAP, US Scheme. Submitter: mpdool2@niap-ccevs.org

**Status:**

[X] On-going certification
[ ] Preparatory/Other

**Certification Deadline Dates: 5 March 2025**
5 March 2025

**SFR or Section of cPP/SD in question: **
8.4.1.5 Management of the Biometric System configuration

**Supporting Document testing in question:**
N/a

**Issue:**
The Biometrics Module version 1.1 references the FMT_SMF_EXT.1 requirement in the Mobile Device Fundamentals PP v3.3 (MDFPP33).  The MDFPP33 does not have this requirement.  The correct requirement reference is FMT_SMF.1.

**Proposed Resolution:**
The TRRT agrees that FMT_SMF.1 is the correct reference. Further, enabling/disabling the BAF is Management Function 22, and not 23 as stated in the Biometrics cPP. This will be sent to the Biometrics iTC for resolution.

**Rationale:**
Consistency amongst documentation

**Comment by woodbe** [comment]
This Technical Decision has been posted to https://biometricitc.github.io/TD/BIO0005.html. You can also see the latest version in the release here: https://github.com/biometricITC/cPP-biometrics/releases/tag/PPM1.1.1.
