### ISSUE TITLE
Attacker profile/motivation

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#62]
From @FGUERINGTO 

In Threats:

As defined in CC §1 A.6.2, “A threat consists of an adverse action   performed by a threat agent on an asset”.    Therefore prior to   define threat, it is useful to define attacker profile and motivation

Suggested Changes:

Local attacker [LA] is unauthorized user of mobile device. He try to access to mobile device and unlock it to access to mobile service using a low attack potential.

Remote attacker [RA] is unauthorized user with remote access using mobile interface try to access to mobile to deactivate access control to remote access to mobile service using a low attack potential (do we want to consider or not ?)

Privacy attacker [PR] is unauthorized user trying to access to sensitive data to disclose them as user identity (Privacy issue) using a low attack potential.

Mobile Owner [MO] official and authorized user, allowed to use mobile service and may act as [ADM].

Note: [MO] is recognized as owner by OEM (purchase and setup procedure) and recognized as owner by MNO (eUICC, UICC => IMSI, KI) => connection is created after owner identity & bank account verification.

Administrator [ADM] perform administration tasks as setup.

Role may be played by [MO].

Mobile user [MU]
[MO] can delegate usage of mobile to [MU] with 2 use cases: 
a) deactivation of authentication (extend period before blocking session & reauthentication request), [MU] run mobile on behalf of [MO]
b) enrol [MU] as mobile user (may require MO deactivation is only a unique user is authorized).

[MO], [MU], [ADM] are considered as trusted user.

**Comment by BrJu** [comment]
Discussed with François:
Use case 1: ok to close
Use case 2+: to be considered

**Comment by FGUERINGTO** [comment]
Use case 1: ok to close
