### ISSUE TITLE
Define asset to protect

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#63]
From @FGUERINGTO 

In Threats:

As defined in CC §1 A.6.2, “A threat consists of an adverse action performed by a threat agent on an asset”. 
Therefore prior to define threat, it is useful to define assets to protect and associated security property (C,I,A,NR…)

Suggested Changes:

Main assets are : 
Protected Mobile Service [PMS] Security property is Access Control [AC].
	
User identity (e.g. pseudonym) [Confidentiality, Integrity, AUthenticity]
	
Biometric data (Features, samples) [Confidentiality, Integrity, AUthenticity, AVailability]
	
Biometric templates [Confidentiality, Integrity, AUthenticity, AVailability]
	
Fall back Mean (Pin, Password, swipe pattern)
TSF data : 
Decision Threshold [I]

**Comment by BrJu** [comment]
Discussed with François:
-Threshold/biometric parameters integrity still seem important.  Will be good to emphasize the need to protect it even if only one is fixed.
-Importance to discuss the other assets for use case 2+

**Comment by woodbe** [comment]
I would agree this is important to protect, but I don't actually see how the TOE itself would provide this protection as it is defined now. I created #118 to try to handle this case.

@FGUERINGTO please review the PR and comment/approve

**Comment by BrJu** [comment]
Addressed by #118
