### ISSUE TITLE
Independent Testing

### ISSUE THREAD

**Issue by BrJu** [biometricITC/cPP-biometrics#67]
How to handle independent testing within a "short" time-boxed approach while still fitting without classical assurance requirements?

Two subtopics:
- performance testing
- PAD testing

**Comment by woodbe** [comment]
Suggest closing this. Performance is being discussed in #109 and PAD is being handled with individual toolboxes.

**Comment by n-kai** [comment]
I agree to close this issue.

**Comment by nils-tekampe** [comment]
I agree

**Comment by woodbe** [comment]
Closed for #109
