### ISSUE TITLE
conformance issue for cPP + MDFPP

### ISSUE THREAD

**Issue by BrJu** [biometricITC/cPP-biometrics#68]
placeholder for future discussion on potential issue with exact conformance in future use cases.

**Comment by woodbe** [comment]
I think we can close this and create a new issue if we determine there are additional considerations when Use Case 2 has actually been completed.

**Comment by nils-tekampe** [comment]
agreed

**Comment by woodbe** [comment]
Agreed to close in 2/14 meeting
