### ISSUE TITLE
Preliminary draft of mobile toolbox for iris for review

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-biometrics#74]
## Preliminary draft of Mobile toolbox for iris

This document is a preliminary draft of mobile toolbox for iris that lists presentation attack test items for mobile iris unlock. Each test item will be refined further to develop attack descriptions. Any comments on this document would be welcomed.

### Introduction
Presentation attack to iris verification is classified into following categories [1]

a) Print attack
Present a genuine iris image printed on a paper to the mobile device
b) Textured contact lenses attack
Attacker wears the textured contact lenses to interfere with iris verification
c) Synthetic Iris Images attack
Present a synthetic iris image created from target user’s iris code
d) Artificial eye attack
Present an artificial eye made of, for example, plastic with counterfeit iris pattern to the device

b) is indeed effective for obfuscating one’s true biometric trait. However, the obfuscating is out of scope of the cPP. In theory, there exist no technical limitations of printing fully opaque cosmetic contact lenses with iris texture of a targeted person and wearing the customized lenses to successfully masquerade as someone else to unlock the device. However, there are no known real-world examples of successful presentation attack of this kind [2] and there are also no research papers to study such kinds of attack. So, b) is out of scope of our evaluation at this moment. c) is also out of scope because we assume that iris code is securely protected by the mobile device. Therefore, this document lists test items related to a) and d).

### Presentation attack test items
The following lists the presentation attack test items. Number of attempts for each PAI and pass criteria should be discussed later, referring the relevant studies (e.g. [10] shows the state of art PAD technique can achieves ACER=2.78).

a)	Attack 1
This attack assumes that attacker can get digital image of target user’s face taken by normal digital camera with visible light.

_Attack method_
Attacker gets [digital image of target user’s face] taken by [digital camera] under [environment] and [preprocess the image], then print out eyes on [paper] with [printer] to [present] it to the mobile device.

Text enclosed in [ ] should be refined further. The following shows my current idea.

[digital image of target user’s face]
Digital image should meet the following condition [3a]:
-	target’s eyes must be bright
-	iris diameter should be more than 75 pixels (more than 175 pixels is ideal)
-	at least 75 % of the iris should be visible

[digital camera]
High resolution digital camera should be used to get clear image of the iris [3b]

[environment]
Controlled environment (the background of the scene is uniform, the light in the office is switched on and the window blinds are down)

[preprocess the image]
For example,
-	extract red channel from the image and convert it into grayscale (green channel is better for some PAD algorithm) [4]
-	crop the eye image and enlarge it to the original size
-	have a hole in a place of the pupil to generate a genuine reflection from the cornea as expected by the sensor [5]

[paper]
Normal paper, mat paper etc [3b], [6]

[printer]
Laser printer or inkjet printer [3b], [6]. At least 1200dpi [7].

[present]
Present the paper under the controlled environment as the same way the user enrolls the iris

_Note_
Evaluator should take a picture of the paper using NIR camera to confirm that the NIR image of the paper contain enough quality of iris pattern before testing.

b)	Attack 2
This attack assumes that attacker can take a photo of target user’s face using a digital camera using NIR.

_Attack method_
Attacker takes [digital image of target user’s face] using [digital camera] under [environment] and [preprocess the image], then print out eyes on [paper] with [printer] to [present] it to the mobile device.

Text enclosed in [ ] should be refined further. The following shows my current idea.

[digital image of target user’s face]
Same as Attack 1

[digital camera]
Normal digital camera that can take NIR image. Attacker can modify the camera to have its IR-blocking filter replaced with a glass plate to take a NIR photo [8], [9]

[environment]
Outdoor environment with sunlight that include NIR. No need to use NIR LED because such attack is considered by Attack 3.

[preprocess the image]
For example,
-	crop the eye image and enlarge it to the original size
-	have a hole in a place of the pupil to generate a genuine reflection from the cornea as expected by the sensor [5]

[paper]
Same as Attack 1

[printer]
Same as Attack 1

[present]
Same as Attack 1

_Note_
Camera’s auto exposure (AE) may not work in the NIR [9]. Evaluator should carefully choose the right one to take a good NIR image referring relevant information in the web

c)	Attack 3
This attack assumes that attacker can take a photo of target user’s face using NIR cameras including commercial iris scanners.

_Attack method_
Attacker takes [digital image of target user’s face] using [NIR camera] under [environment] and [preprocess the image], then print out eyes on [paper] with [printer] to [present] it to the mobile device.

Text enclosed in [ ] should be refined further. The following show my current idea.

[digital image of target user’s face]
Same as Attack 1

[NIR camera]
Commercial iris scanner [10]

[environment]
Controlled environment

[preprocess the image]
Same as Attack 2

[paper]
Same as Attack 1

[printer]
Same as Attack 1

[present]
Present the paper under the controlled environment as the same way the user enrolls the iris. Attacker may place a contact lens over the iris image to give the iris scanner the curvature it's expecting from a real eye [8]

d)	Attack 4
Same as Attack 3 except that attacker attach the captured iris pattern to the artificial eyes.

_Attack method_
Attacker takes [digital image of target user’s face] using [NIR camera] under [environment] and [preprocess the image], then print out eyes on [paper] with [printer] and attach the iris image to [artificial eye] to [present] it to the mobile device.

[digital image of target user’s face]
Same as Attack 3

[NIR camera]
Same as Attack 3

[environment]
Same as Attack 3

[preprocess the image]
Same as Attack 3

[paper]
Same as Attack 3

[printer]
Same as Attack 3

[artificial eye]
Create one referring [1]

[present]
Same as Attack 3

### Reference
[1] Learning Hierarchical Visual Codebook for Iris Liveness Detection
http://www.csis.pace.edu/~ctappert/dps/2011IJCB/papers/226.pdf
[2] Contact lens detection in iris images
http://jultika.oulu.fi/files/nbnfi-fe201801222182.pdf
[3a] Hacking Putin's Eyes: How To Bypass Biometrics The Cheap And Dirty Way With Google Images
https://www.forbes.com/sites/thomasbrewster/2015/03/05/clone-putins-eyes-using-google-images/#35160438214a
[3b] Robust Scheme for Iris Presentation Attack Detection Using Multiscale Binarized Statistical Image Features
http://ieeexplore.ieee.org/document/7031897/
[4] Cross-spectral Iris Recognition for Mobile Applications using High-quality Color Images
https://pdfs.semanticscholar.org/349f/a8805e9d5f7d4096fb605453a90877f15ae9.pdf
[5] LivDet Iris 2017 - Iris Liveness Detection Competition 2017
http://iab-rubric.org/papers/Yambay-IJCB17-LiveDET.pdf
[6] Database of Iris Printouts and its Application: Development of Liveness Detection Method for Iris Recognition
http://zbum.ia.pw.edu.pl/PAPERS/MMAR_2013_Czajka.pdf
[7] Spoofing iris recognition technology with pictures
http://www.biometricupdate.com/201503/spoofing-iris-recognition-technology-with-pictures
[8] Samsung Galaxy S8 Iris Scanner Hacked In Three Simple Steps
https://www.forbes.com/sites/ianmorris/2017/05/23/samsung-galaxy-s8-iris-scanner-hacked-in-three-simple-steps/#5151feb4ccba
[9] The physics of near-infrared photography
http://www.montana.edu/jshaw/documents/NIR%20Photography%20-%20Mangold%20et%20al%20-%20EJP2013.pdf
[10] Presentation attack detection using a generalizable statistical approach for periocular and iris systems
https://dl.gi.de/bitstream/handle/20.500.12116/1244/111.pdf?sequence=1&isAllowed=y

**Comment by n-kai** [comment]
I agree to close this and #72 and dicuss based on actual toolbox.

**Comment by woodbe** [comment]
Closed. Further discussions handled in newer issues directly related to the appropriate toolbox.
