### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by woodbe** [biometricITC/cPP-biometrics#79]
https://github.com/nils-tekampe/cPP-biometrics/blob/master/input/architecture.png

I uploaded this diagram responding to the need for some sort of sample architecture referencing a mobile device. Since the mobile devices I know of today do not use external biometric components, I didn't draw that in, I expected everything would be done in a self-contained manner on the device. I didn't give a lot of detail, but some basic points here that should work for the devices I know.

To be clear on it, if you start with the user making a request that needs authentication (an app or the device), then from that starting point, the app (or login service) would call to OS Biometric API layer.

The OS Biometric Layer could be simple or complex, but mainly it is the standardized API provided for the system to access the biometric components. This may also provide some UI elements (such as prompts to the user about the process) or these may be left to the subsystem (i.e. the TOE), depending on the implementation. I show the display hardware inside the SOE (which it usually is for DRM purposes), but that is not a critical component here, just one implementation example.

The OS Biometric Layer then calls to the TOE inside the Secure Operating Environment. I didn't bother to show any actions to the SOE (such as storage) since the TOE is completely contained within the SOE, and relies on its capabilities for storage, processing, crypto, etc.

Once the request to authenticate has reached the TOE, the user would provide their sample, captured by the sensor component of the TOE and perform the processing. The result passed back to the OS Biometric API layer and then to the app/OS to allow or block the user.

Obviously this would be similar for enrollment, etc, I just did it for an auth attempt as the simple version to follow.

**Comment by woodbe** [comment]
I have uploaded my updated image files based on my original file and the changes from @BrJu. I have uploaded a PNG, PDF and the original Visio file to the images folder.

**Comment by BrJu** [comment]
Looks good for use case 1. To be reviewed on meeting 20180607

**Comment by stemotre** [comment]
As exposed in issue #119, the proposed architecture diagram shall discuss plaintext storage in SEE versus secure storage outside SEE (and cPP define “secure" and responsibility of TOE/TSF).
Actually, the SEE boundaries are not relevant to this cPP unless the SEE inherited requirements are clearly addressed and part of this cPP (either requirements or I believe environment objectives).
Attached are two updates that reflect the current state of the cPP (which we have an issue with) and a TOE centric version: with SEE and without.

[Bio cPP TOE architecture diagram - WITH SEE.pptx](https://github.com/biometricITC/cPP-biometrics/files/2077474/Bio.cPP.TOE.architecture.diagram.-.WITH.SEE.pptx)
<img width="845" alt="bio cpp toe architecture diagram - without see" src="https://user-images.githubusercontent.com/34280505/41055406-143a0dd0-6976-11e8-9e54-322553270a91.png">

**Comment by stemotre** [comment]
As exposed in issue #119, the proposed architecture diagram shall discuss plaintext storage in SEE versus secure storage outside SEE (and cPP define “secure" and responsibility of TOE/TSF).
Actually, the SEE boundaries are not relevant to this cPP unless the SEE inherited requirements are clearly addressed and part of this cPP (either requirements or I believe environment objectives).
Attached are two updates that reflect the current state of the cPP (which we have an issue with) and a TOE centric version: with SEE and without.

<img width="911" alt="bio cpp toe architecture diagram - with see" src="https://user-images.githubusercontent.com/34280505/41055518-6abdb314-6976-11e8-818a-86313e9ee910.png">

<img width="845" alt="bio cpp toe architecture diagram - without see" src="https://user-images.githubusercontent.com/34280505/41055519-6d4ad9ea-6976-11e8-9fe6-f0b6d56e4386.png">

**Comment by woodbe** [comment]
How about this as the updated architecture (based on the call and changes).

![image](https://user-images.githubusercontent.com/19575297/41119118-f3499736-6a5f-11e8-81d2-0c7772ef8680.png)

**Comment by BrJu** [comment]
Solved -- the PR has been merged
