### ISSUE TITLE
Preliminary draft of supporting documents for the cPP

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-biometrics#81]
Draft is incomplete and may not be mature enough but I uploaded the draft to give more clear picture of evaluation based on the cPP.

Please look at from "Evaluation Activities for SFRs". Text before that was copied from another cPP so you don't need to review them.

https://github.com/nils-tekampe/cPP-biometrics/blob/master/input/BS%20SD.md

Any comment would be welcomed

**Comment by BrJu** [comment]
not really an open issue, so closing.
On-going drafts for methodology are available here
