### ISSUE TITLE
change request to the cPP

### ISSUE THREAD

**Issue by n-kai** [biometricITC/cPP-biometrics#85]
I have the following change proposals to the latest cPP to sync it with the latest SD (https://github.com/nils-tekampe/cPP-biometrics/blob/NKAI-April-05/input/BS%20SD.md)

**CP1**
Replace
_FPT_BDP_EXT.1 Biometric data processing
FPT_BDP_EXT.1.1 The TSF shall process any plaintext biometric data used to generate templates and perform sample matching, except publicly accessible biometric data, within the security boundary of the secure execution environment._

_FPT_BDP_EXT.3 Biometric data storage
FPT_BDP_EXT.3.1 The TSF shall not store any plaintext biometric data except publicly accessible biometric data outside the secure execution environment._

with
_FPT_BDP_EXT.1 Biometric data processing
FPT_BDP_EXT.1.1 The TSF shall process any plaintext biometric data used to generate templates and perform sample matching, except [assignment: list of publicly accessible biometric data], within the security boundary of the secure execution environment._

_FPT_BDP_EXT.3 Biometric data storage
FPT_BDP_EXT.3.1 The TSF shall not store any plaintext biometric data except [assignment: list of publicly accessible biometric data] outside the secure execution environment._

**Rationale**
“publicly accessible biometric data” should be defined accurately by the ST author.  

**CP2**
Replace
_FPT_BDP_EXT.2 No Biometric data transmission
FPT_BDP_EXT.2.1 The TSF shall not transmit any plaintext biometric data except publicly accessible biometric data outside the security boundary of the secure execution environment._

with
_FPT_BDP_EXT.2 No Biometric data transmission
FPT_BDP_EXT.2.1 The TSF shall not transmit any plaintext biometric data outside the security boundary of the secure execution environment._

**Rationale**
Biometric data is sensitive personal data and publicly accessible biometric data (e.g. face image) shall not be transmitted to any entities outside the SEE without a consent from users.

**Comment by BrJu** [comment]
"My opinion is that anything that is taken by the TOE for the purpose of generating a biometric template or as a sample to match to a template is not really "public" data since it should only be available inside the TOE. As such, I would remove the "except publicaly accessible biometric data" from the original one as my suggested modification."

I support this removal. The TOE should not make any distinction between the processed biometric data.

**Comment by BrJu** [comment]
cf. changed made in #118 for FPT_BDP_EXT.3.1. 
(the use of "except publicaly accessible biometric data" should be checked elsewhere in the cPP)

**Comment by BrJu** [comment]
Addressed by #118  -- and once merged we have to check that "except publicly ..." is not used anymore   [ @BrJu will create a PR if needed]

**Comment by BrJu** [comment]
Closed as the last comment is now covered by #122
