### ISSUE TITLE
EA for FIA_MBV_EXT.1, independent testing

### ISSUE THREAD

**Issue by nils-tekampe** [biometricITC/cPP-biometrics#93]
Current version of SD reads as follows for FIA_MBV_EXT.1:

_The evaluator shall solely rely on the supplementary information (developer’s performance test document) to achieve this objective following instruction defined in Assessment strategy._

I would suggest that the evaluator should make his/her own test in this context and not only rely on the results of the vendor.

**Comment by woodbe** [comment]
This has since been handled in v1.0
