### ISSUE TITLE
EA for FIA_MBV_EXT.1, statistical significance

### ISSUE THREAD

**Issue by nils-tekampe** [biometricITC/cPP-biometrics#94]
Current version of SD for FIA_MBV_EXT.1 reads:

_Therefore, risk of zero-effort impostor attempts is low and the developer may not follow the statistical method (e.g. Rule of 3 or Rule of 30) to measure the mobile biometric verification performance._

I disagree in this point. Even if the attack potential is limited, the test should consider basic statistic principles.

**Comment by woodbe** [comment]
This has been answered in v1.0
