### ISSUE TITLE
Proposal to update OE.Protection

### ISSUE THREAD

**Issue by FGUERINGTO** [biometricITC/cPP-biometrics#97]
Current text of OE.Protection should be improved. 
"The TOE environment shall ensure that the TOE and its biometric data is adequately protected."
here my proposal : 
"The TOE environment shall ensure that the TOE is adequately protected during storage and execution and biometric data is adequately protected during handling and storage."

**Comment by BrJu** [comment]
Discussed with François:
Should we change biometric data into biometric template? (only biometric template [may go] goes outside the TOE)
We should clarify whether "with support from the TOE environment" is optional or mandatory? 

To be reworked together with #98

**Comment by woodbe** [comment]
So in my thinking keeping this as "biometric data" means that the TOE needs to protect the samples and any interim steps to the creation of the template, not just the template, so I don't really like changing it to the template alone.

Also, I'm not really sure about what is meant by the template going outside the TOE. My expectation, for use case 1 on mobile (or even GPOS) is that the matching is all done locally and is contained inside what is considered to be the boundary of the TOE. To that end, what exactly is meany by the template going outside of the TOE. If this is getting into storage, I though we had already dealt with this as part of the environment where the TOE is located.

Lastly, I don't think anyone would object if the TOE has its own protection, but for the mobile device case where the TOE is a tightly integrated component, I don't know if it makes sense to assume this is optional, it just is.

**Comment by BrJu** [comment]
The comment comes from the reading of both O.Protection and OE.protection in parallel. 
One is saying that the TOE is responsible (okay, using environment, but does not disallow the TOE to use its own mechanism), the other that the environment is ensuring the security is adequate.   We apparently need to clarify the link and the intersection between TOE and environment responsibilities.  
So why François made the comments that the TOE is responsible of protection during usage and environment is responsible during storage.

PS: the proposed change from data to template is a refinement in case we consider that environment is responsible only for storage.

**Comment by n-kai** [comment]
**O.Protection**
The TOE shall protect biometric data except publicly accessible biometric data using security functions provided by the TOE environment.
**OE.Protection**
The TOE environment shall ensure that the TOE and biometric data is adequately protected.

I agree with @FGUERINGTO . O.Protection and OE.Protection has some overlap. I propose to deal with #119 first to clarify the relationship between the TOE and TOE env (i.e. SEE).

**Comment by n-kai** [comment]
this issue will be fixed with pull request for #119 at the same time.

**Comment by BrJu** [comment]
Addressed by #118
