### ISSUE TITLE
Proposal to update O.Protection

### ISSUE THREAD

**Issue by FGUERINGTO** [biometricITC/cPP-biometrics#98]
text of O.Protection is misleading. 
"The TOE shall protect biometric data except publicly accessible biometric data using security functions provided by the TOE environment."

My proposal is : "The TOE shall protect biometric data confidentiality (when required) and integrity during usage."

**Comment by BrJu** [comment]
Discussed with François:
Correlation with #97 to be clarified

**Comment by BrJu** [comment]
addressed by #118
