### ISSUE TITLE
Proposal for update of O.BIO_Verification

### ISSUE THREAD

**Issue by FGUERINGTO** [biometricITC/cPP-biometrics#99]
Current text of O.BIO_Verification should be improved.
"The TOE shall provide a mobile biometric verification mechanism to authenticate a user with an adequate reliability. The TOE shall meet the relevant criteria for its security relevant error rates for mobile biometric verification. "
My proposal: 
The TOE shall provide a mobile biometric verification mechanism comparing with an adequate reliability Biometric Data captured from user with reference Data imported in TOE from TOE environment. The TOE shall meet the relevant criteria for its security relevant error rates for mobile biometric verification.

Application note : comparison is done with Biometric Data captured from user using sensor embedded in TOE, then such data are computed by TOE and compared with Biometric reference Data imported in TOE from storage done in TOE environment.

Is there a way to avoid multiple presentations when result of comparison is wrong ?
is it covered by TOE or TOE environment ?

**Comment by BrJu** [comment]
Current definition is here https://github.com/biometricITC/cPP-biometrics/blob/master/3_ProtectionProfile/Bio%20cPP.md#obio_verification

**Comment by nils-tekampe** [comment]
I agree with @woodbe and would suggest to close this issue without any change to the document

**Comment by BrJu** [comment]
Discussed with François: ok

**Comment by n-kai** [comment]
We agree to close this issue on 7th June. please close this issue
